export type WordTier = 'short' | 'medium' | 'long';

// Short words: 3–4 characters
const SHORT_WORDS: string[] = [
  'ace', 'act', 'add', 'age', 'ago', 'aid', 'aim', 'air', 'ale', 'ant',
  'ape', 'arc', 'arm', 'art', 'ask', 'ate', 'axe', 'bad', 'bag', 'ban',
  'bar', 'bat', 'bay', 'bed', 'bet', 'bid', 'big', 'bit', 'bow', 'box',
  'boy', 'bug', 'bus', 'buy', 'cab', 'can', 'cap', 'car', 'cat', 'cop',
  'cow', 'cry', 'cup', 'cut', 'dad', 'dam', 'day', 'den', 'dig', 'dim',
  'dip', 'dog', 'dot', 'dry', 'due', 'dug', 'ear', 'eat', 'egg', 'ego',
  'elf', 'elm', 'end', 'era', 'eve', 'eye', 'fan', 'far', 'fat', 'fee',
  'few', 'fig', 'fit', 'fix', 'fly', 'fog', 'for', 'fox', 'fun', 'fur',
  'gap', 'gas', 'gel', 'gem', 'get', 'god', 'got', 'gun', 'gut', 'guy',
  'gym', 'had', 'ham', 'has', 'hat', 'hay', 'hen', 'her', 'hid', 'him',
  'hip', 'his', 'hit', 'hop', 'hot', 'how', 'hub', 'hug', 'hum', 'hut',
  'ice', 'icy', 'ill', 'imp', 'ink', 'inn', 'ion', 'ivy', 'jab', 'jam',
  'jar', 'jaw', 'jet', 'job', 'jog', 'joy', 'jug', 'key', 'kid', 'kin',
  'kit', 'lab', 'lad', 'lag', 'lap', 'law', 'lay', 'led', 'leg', 'let',
  'lid', 'lip', 'lit', 'log', 'lot', 'low', 'mad', 'man', 'map', 'mat',
  'mob', 'mod', 'mom', 'mop', 'mud', 'mug', 'nap', 'net', 'nod', 'nor',
  'not', 'now', 'nun', 'oak', 'odd', 'off', 'oil', 'old', 'one', 'opt',
  'orb', 'ore', 'our', 'out', 'own', 'pad', 'pan', 'paw', 'pay', 'pen',
  'pet', 'pie', 'pig', 'pin', 'pit', 'pod', 'pop', 'pot', 'pry', 'pub',
  'pug', 'pun', 'pup', 'put', 'ram', 'ran', 'rap', 'rat', 'raw', 'ray',
  'red', 'ref', 'rep', 'rid', 'rig', 'rip', 'rob', 'rod', 'rot', 'row',
  'rub', 'rug', 'rum', 'run', 'rut', 'sad', 'sag', 'sat', 'saw', 'say',
  'sea', 'set', 'sew', 'shy', 'sin', 'sip', 'sir', 'sit', 'six', 'ski',
  'sky', 'sly', 'sob', 'sod', 'son', 'sow', 'spy', 'sub', 'sue', 'sum',
  'sun', 'tab', 'tan', 'tap', 'tar', 'tax', 'tea', 'ten', 'the', 'tie',
  'tin', 'tip', 'toe', 'ton', 'too', 'top', 'tow', 'toy', 'try', 'tub',
  'tug', 'two', 'urn', 'use', 'van', 'vat', 'vow', 'wad', 'war', 'was',
  'wax', 'web', 'wed', 'wet', 'who', 'why', 'wig', 'win', 'wit', 'woe',
  'wok', 'won', 'woo', 'yam', 'yap', 'yew', 'you', 'zap', 'zen', 'zip',
  // 4-letter words
  'able', 'acid', 'aged', 'also', 'area', 'army', 'away', 'baby', 'back',
  'bail', 'bake', 'bald', 'ball', 'band', 'bane', 'bank', 'bare', 'bark',
  'barn', 'base', 'bash', 'bass', 'bath', 'bear', 'beat', 'beef', 'been',
  'beer', 'bell', 'belt', 'bend', 'best', 'bike', 'bill', 'bind', 'bird',
  'bite', 'blot', 'blow', 'blue', 'blur', 'boar', 'boat', 'bold', 'bolt',
  'bone', 'book', 'boom', 'boot', 'bore', 'born', 'both', 'brag', 'brat',
  'brew', 'brim', 'buck', 'bulk', 'bull', 'bump', 'burn', 'burp', 'cage',
  'cake', 'call', 'calm', 'came', 'camp', 'card', 'care', 'cart', 'case',
  'cash', 'cast', 'cave', 'cell', 'chat', 'chip', 'chop', 'city', 'clad',
  'clam', 'clap', 'claw', 'clay', 'clip', 'club', 'clue', 'coal', 'coat',
  'code', 'coil', 'coin', 'cold', 'colt', 'come', 'cone', 'cook', 'cool',
  'copy', 'cord', 'core', 'corn', 'cost', 'cozy', 'crab', 'crew', 'crop',
  'crow', 'curl', 'cute', 'dark', 'dart', 'data', 'date', 'dawn', 'dead',
  'deal', 'dear', 'deck', 'deed', 'deep', 'deer', 'deft', 'deny', 'desk',
  'dial', 'dice', 'diet', 'dirt', 'disk', 'dive', 'dock', 'dome', 'done',
  'door', 'dorm', 'dove', 'down', 'draw', 'drew', 'drip', 'drop', 'drug',
  'drum', 'duke', 'dull', 'dune', 'dusk', 'dust', 'duty', 'each', 'earl',
  'earn', 'ease', 'east', 'easy', 'edge', 'else', 'emit', 'epic', 'even',
  'ever', 'evil', 'exam', 'face', 'fact', 'fade', 'fail', 'faint', 'fair',
  'fake', 'fall', 'fame', 'farm', 'fast', 'fate', 'fear', 'feat', 'feed',
  'feel', 'feet', 'fell', 'felt', 'file', 'fill', 'film', 'find', 'fine',
  'fire', 'firm', 'fish', 'fist', 'flag', 'flat', 'flaw', 'flea', 'flew',
  'flip', 'flow', 'foam', 'fold', 'folk', 'fond', 'font', 'food', 'fool',
  'foot', 'ford', 'fore', 'fork', 'form', 'fort', 'foul', 'four', 'free',
  'from', 'fuel', 'full', 'fume', 'fuse', 'fuss', 'gale', 'game', 'gang',
  'gate', 'gave', 'gaze', 'gear', 'gene', 'gild', 'gill', 'gist', 'give',
  'glad', 'glow', 'glue', 'goal', 'goat', 'goes', 'gold', 'golf', 'gone',
  'good', 'grab', 'gram', 'gray', 'grew', 'grid', 'grim', 'grin', 'grip',
  'grow', 'gulf', 'gust', 'hack', 'hail', 'half', 'hall', 'hand', 'hang',
  'hard', 'hare', 'harm', 'harp', 'hate', 'hawk', 'head', 'heal', 'heap',
  'hear', 'heat', 'heel', 'held', 'help', 'herb', 'here', 'hero', 'hide',
  'high', 'hill', 'hint', 'hire', 'hole', 'home', 'hone', 'hook', 'hoop',
  'hope', 'horn', 'hose', 'hour', 'hull', 'hunt', 'hurt', 'hymn', 'icon',
  'idea', 'idle', 'inch', 'into', 'iron', 'isle', 'item', 'jolt', 'jump',
  'just', 'keen', 'keep', 'kill', 'kind', 'king', 'knew', 'knit', 'knob',
  'knot', 'know', 'lack', 'lake', 'lamb', 'lamp', 'land', 'lane', 'lark',
  'last', 'late', 'lava', 'lawn', 'lead', 'leaf', 'lean', 'leap', 'lend',
  'less', 'life', 'lift', 'like', 'lime', 'line', 'link', 'lion', 'list',
  'live', 'load', 'loan', 'lock', 'loft', 'lone', 'long', 'look', 'loom',
  'loon', 'loop', 'lore', 'lose', 'loss', 'lost', 'love', 'luck', 'lull',
  'lump', 'lung', 'lure', 'lurk', 'made', 'mail', 'main', 'make', 'male',
  'mall', 'mane', 'mark', 'mars', 'mast', 'mate', 'meal', 'mean', 'meat',
  'meet', 'melt', 'memo', 'menu', 'mere', 'mild', 'mile', 'milk', 'mill',
  'mime', 'mind', 'mine', 'mint', 'miss', 'mist', 'mode', 'mole', 'mood',
  'moon', 'more', 'most', 'move', 'much', 'mule', 'muse', 'must', 'mute',
  'myth', 'nail', 'name', 'navy', 'near', 'neck', 'need', 'nest', 'news',
  'next', 'nice', 'nine', 'node', 'nose', 'note', 'numb', 'obey', 'once',
  'only', 'open', 'over', 'page', 'paid', 'pale', 'palm', 'park', 'part',
  'pass', 'past', 'path', 'pave', 'peak', 'pear', 'peel', 'peer', 'pick',
  'pine', 'pink', 'pipe', 'plan', 'play', 'plot', 'plow', 'plug', 'plum',
  'plus', 'poem', 'poet', 'pole', 'poll', 'pond', 'pool', 'poor', 'pore',
  'port', 'pose', 'post', 'pour', 'pray', 'prey', 'prod', 'prop', 'pull',
  'pump', 'pure', 'push', 'quit', 'quiz', 'race', 'rack', 'rage', 'raid',
  'rail', 'rain', 'rake', 'rank', 'rare', 'rash', 'rate', 'rave', 'read',
  'real', 'reap', 'reel', 'rely', 'rent', 'rest', 'rice', 'rich', 'ride',
  'rife', 'ring', 'riot', 'rise', 'risk', 'road', 'roam', 'roar', 'rock',
  'role', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'rude', 'rule',
  'rush', 'rust', 'sage', 'sail', 'sake', 'sale', 'salt', 'same', 'sand',
  'sane', 'sang', 'sank', 'save', 'scan', 'scar', 'seal', 'seam', 'seat',
  'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send', 'sent', 'shed',
  'ship', 'shoe', 'shop', 'shot', 'show', 'shut', 'sick', 'side', 'sigh',
  'sign', 'silk', 'sill', 'sing', 'sink', 'site', 'size', 'skin', 'skip',
  'slab', 'slam', 'slap', 'slim', 'slip', 'slot', 'slow', 'slug', 'slum',
  'snag', 'snap', 'snip', 'snow', 'soak', 'soap', 'soar', 'sock', 'soft',
  'soil', 'sold', 'sole', 'some', 'song', 'soon', 'soot', 'sore', 'sort',
  'soul', 'soup', 'span', 'spar', 'spin', 'spit', 'spot', 'spur', 'star',
  'stay', 'stem', 'step', 'stew', 'stir', 'stop', 'stub', 'stun', 'such',
  'suit', 'sung', 'sunk', 'sure', 'swan', 'swap', 'sway', 'swim', 'tail',
  'tale', 'tall', 'tame', 'task', 'tell', 'temp', 'tend', 'term', 'test',
  'text', 'than', 'that', 'them', 'then', 'they', 'thin', 'this', 'thorn',
  'thus', 'tide', 'tidy', 'tier', 'tile', 'till', 'time', 'tiny', 'tire',
  'toad', 'toll', 'tomb', 'tome', 'tone', 'tong', 'took', 'tool', 'torn',
  'toss', 'tour', 'town', 'trek', 'trim', 'trip', 'trod', 'true', 'tube',
  'tuck', 'tuft', 'tune', 'turf', 'turn', 'twig', 'twin', 'type', 'ugly',
  'undo', 'unit', 'unto', 'upon', 'urge', 'used', 'user', 'vane', 'vary',
  'vast', 'veil', 'vein', 'very', 'vest', 'vice', 'view', 'vine', 'void',
  'volt', 'vote', 'wade', 'wage', 'wake', 'walk', 'wall', 'wand', 'want',
  'ward', 'warm', 'warn', 'warp', 'wart', 'wave', 'weak', 'weal', 'wean',
  'wear', 'weld', 'well', 'went', 'were', 'west', 'what', 'when', 'whim',
  'whip', 'wide', 'wife', 'wild', 'will', 'wilt', 'wind', 'wine', 'wing',
  'wink', 'wire', 'wise', 'wish', 'with', 'wolf', 'wood', 'wool', 'word',
  'wore', 'work', 'worm', 'wren', 'writ', 'yank', 'yard', 'yarn', 'year',
  'yell', 'your', 'zero', 'zone', 'zoom',
];

// Medium words: 5–7 characters
const MEDIUM_WORDS: string[] = [
  'abbey', 'abide', 'abyss', 'acorn', 'acute', 'adapt', 'adept', 'admit',
  'adopt', 'adult', 'aegis', 'after', 'again', 'agent', 'agile', 'agony',
  'agree', 'ahead', 'aisle', 'alarm', 'album', 'alert', 'algae', 'align',
  'alike', 'alive', 'aloft', 'alone', 'along', 'aloof', 'aloud', 'alpha',
  'altar', 'alter', 'among', 'ample', 'angel', 'anger', 'angle', 'angry',
  'angst', 'anime', 'ankle', 'annex', 'antic', 'anvil', 'apart', 'apple',
  'apply', 'apron', 'aptly', 'arbor', 'ardor', 'arise', 'armor', 'aroma',
  'array', 'arrow', 'asset', 'attic', 'audit', 'aunty', 'avail', 'avoid',
  'awake', 'award', 'aware', 'awful', 'azure', 'badge', 'baker', 'basic',
  'basis', 'batch', 'beach', 'began', 'begin', 'being', 'below', 'bench',
  'berry', 'birch', 'bison', 'black', 'blade', 'blame', 'bland', 'blank',
  'blaze', 'bleak', 'blend', 'bless', 'blimp', 'blind', 'bliss', 'block',
  'blood', 'bloom', 'blown', 'blunt', 'board', 'boost', 'booth', 'boxer',
  'brace', 'braid', 'brain', 'brake', 'brand', 'brave', 'bread', 'break',
  'breed', 'brick', 'bride', 'brief', 'bring', 'brisk', 'broad', 'brook',
  'broth', 'brown', 'brush', 'brute', 'bugle', 'build', 'built', 'bulge',
  'bully', 'bunch', 'bunny', 'burst', 'buyer', 'camel', 'candy', 'cargo',
  'carry', 'carve', 'cedar', 'chain', 'chair', 'chalk', 'champ', 'chant',
  'chaos', 'chard', 'charm', 'chart', 'chase', 'cheap', 'check', 'cheek',
  'cheer', 'chess', 'chest', 'chief', 'child', 'choir', 'chord', 'cinch',
  'civic', 'civil', 'claim', 'clash', 'clasp', 'class', 'clean', 'clear',
  'clerk', 'click', 'cliff', 'climb', 'cling', 'clock', 'close', 'cloth',
  'cloud', 'clump', 'coach', 'coast', 'comet', 'comic', 'comma', 'conch',
  'coral', 'couch', 'could', 'count', 'court', 'cover', 'craft', 'crane',
  'crash', 'crawl', 'creak', 'creek', 'crest', 'crime', 'crisp', 'croak',
  'cross', 'crowd', 'crown', 'crude', 'cruel', 'crush', 'crust', 'crypt',
  'cubic', 'curve', 'cycle', 'dairy', 'daisy', 'dance', 'delta', 'depot',
  'depth', 'derby', 'devil', 'digit', 'dimly', 'dingy', 'dirge', 'dirty',
  'disco', 'ditch', 'divvy', 'dizzy', 'doing', 'doubt', 'dough', 'dowel',
  'dozen', 'drain', 'drape', 'dread', 'dream', 'dress', 'dried', 'drift',
  'drill', 'drink', 'drive', 'drove', 'drown', 'dryer', 'duchy', 'dwarf',
  'dwell', 'dying', 'eagle', 'early', 'earth', 'eight', 'elder', 'elbow',
  'email', 'ember', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'envoy',
  'equal', 'error', 'essay', 'ether', 'event', 'every', 'exact', 'extra',
  'fable', 'facet', 'faint', 'fairy', 'false', 'fancy', 'feast', 'felon',
  'fence', 'ferry', 'fever', 'fiber', 'field', 'fiend', 'fifth', 'fifty',
  'fight', 'final', 'first', 'fjord', 'flake', 'flame', 'flash', 'flask',
  'fleet', 'flesh', 'float', 'flock', 'flood', 'floor', 'flour', 'fluid',
  'fluke', 'flute', 'focal', 'foggy', 'forge', 'forth', 'forty', 'forum',
  'foyer', 'frame', 'frank', 'fraud', 'freak', 'fresh', 'frond', 'front',
  'frost', 'froze', 'fruit', 'fully', 'fungi', 'funky', 'funny', 'gauze',
  'gavel', 'given', 'gland', 'glare', 'glass', 'gleam', 'glean', 'glide',
  'gloom', 'glory', 'gloss', 'glove', 'gnome', 'going', 'gouge', 'grace',
  'grade', 'grain', 'grand', 'grant', 'grape', 'grasp', 'grass', 'grate',
  'graze', 'great', 'greed', 'green', 'greet', 'grief', 'groan', 'groin',
  'groom', 'groove', 'gross', 'group', 'grove', 'grown', 'gruel', 'grunt',
  'guard', 'guava', 'guess', 'guide', 'guild', 'guile', 'guise', 'gusto',
  'gusty', 'gypsy', 'habit', 'haiku', 'happy', 'harsh', 'haste', 'hasty',
  'haven', 'hazel', 'heart', 'heavy', 'hedge', 'hello', 'hence', 'herbs',
  'heron', 'hinge', 'hippo', 'hoist', 'holly', 'homer', 'honey', 'honor',
  'horse', 'hotel', 'house', 'hover', 'humid', 'hunky', 'hurry', 'husky',
  'hutch', 'ideal', 'image', 'imply', 'inbox', 'index', 'inner', 'input',
  'inter', 'intro', 'inure', 'irate', 'irony', 'issue', 'ivory', 'jazzy',
  'jewel', 'joint', 'joker', 'joust', 'judge', 'juice', 'juicy', 'karma',
  'knife', 'knock', 'known', 'koala', 'label', 'lance', 'large', 'laser',
  'latch', 'later', 'laugh', 'layer', 'learn', 'lease', 'ledge', 'legal',
  'lemon', 'level', 'light', 'lilac', 'limit', 'liner', 'linen', 'liver',
  'llama', 'local', 'lodge', 'logic', 'loose', 'lorry', 'lover', 'lower',
  'loyal', 'lucid', 'lucky', 'lunch', 'lyric', 'magic', 'major', 'maker',
  'maple', 'march', 'match', 'mayor', 'media', 'mercy', 'merge', 'merit',
  'merry', 'metal', 'might', 'model', 'money', 'month', 'moose', 'moral',
  'mount', 'mouse', 'mouth', 'movie', 'muddy', 'music', 'musty', 'naive',
  'nasty', 'natty', 'naval', 'nerve', 'never', 'nicer', 'night', 'ninja',
  'nitro', 'noble', 'noise', 'north', 'novel', 'nurse', 'nymph', 'occur',
  'ocean', 'offer', 'often', 'olive', 'onset', 'opera', 'orbit', 'order',
  'organ', 'other', 'otter', 'ought', 'outdo', 'outer', 'outwit', 'ovoid',
  'owner', 'ozone', 'paint', 'panda', 'panic', 'paper', 'party', 'pasta',
  'patch', 'pause', 'peace', 'peach', 'penny', 'peril', 'perky', 'phase',
  'phone', 'photo', 'piano', 'piece', 'pilot', 'pinch', 'pixel', 'pizza',
  'place', 'plain', 'plane', 'plant', 'plate', 'plaza', 'plead', 'pluck',
  'plumb', 'plume', 'plunge', 'point', 'polar', 'poppy', 'porch', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prism', 'prize',
  'probe', 'prone', 'proof', 'prose', 'prove', 'prowl', 'prune', 'psalm',
  'pudgy', 'pupil', 'purse', 'pygmy', 'queen', 'query', 'quest', 'queue',
  'quick', 'quiet', 'quota', 'quote', 'radar', 'radio', 'rainy', 'rally',
  'ranch', 'range', 'rapid', 'rated', 'ratio', 'reach', 'realm', 'rebus',
  'recap', 'reign', 'relax', 'remix', 'repay', 'reset', 'rider', 'risky',
  'rival', 'river', 'rivet', 'robot', 'rocky', 'rogue', 'roman', 'rouge',
  'rough', 'round', 'route', 'rowdy', 'royal', 'rugby', 'ruler', 'rupee',
  'rusty', 'sadly', 'sagas', 'salad', 'sally', 'salon', 'salvo', 'sauce',
  'savvy', 'scald', 'scale', 'scalp', 'scant', 'scare', 'scary', 'scene',
  'scone', 'scope', 'score', 'scout', 'scram', 'scrap', 'scrub', 'seize',
  'serve', 'setup', 'seven', 'shard', 'shark', 'sharp', 'sheen', 'sheer',
  'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shore',
  'short', 'shout', 'shove', 'shrub', 'shuck', 'sight', 'since', 'sixth',
  'sixty', 'skill', 'skimp', 'skunk', 'slate', 'slave', 'sleep', 'sleet',
  'sleek', 'slice', 'slide', 'slope', 'slosh', 'sloth', 'slump', 'slunk',
  'small', 'smart', 'smash', 'smile', 'smite', 'smoke', 'snail', 'snake',
  'snare', 'sneak', 'sneer', 'sniff', 'solar', 'solid', 'solve', 'south',
  'space', 'spade', 'spare', 'spark', 'spawn', 'speak', 'spear', 'speck',
  'speed', 'spend', 'spice', 'spill', 'spine', 'spite', 'splat', 'spoil',
  'spook', 'spoon', 'spore', 'sport', 'spray', 'squad', 'squat', 'squid',
  'stack', 'stage', 'stain', 'stale', 'stall', 'stamp', 'stand', 'stank',
  'start', 'starve', 'state', 'steal', 'steam', 'steel', 'steep', 'steer',
  'stern', 'stick', 'still', 'sting', 'stock', 'stomp', 'stone', 'stood',
  'store', 'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'stray',
  'strip', 'strum', 'strut', 'study', 'stuff', 'stump', 'style', 'suave',
  'sugar', 'suite', 'super', 'surge', 'swamp', 'sweep', 'sweet', 'swept',
  'swift', 'swipe', 'swirl', 'swore', 'sworn', 'swung', 'synth', 'syrup',
  'table', 'talon', 'tango', 'tapir', 'taunt', 'teach', 'tense', 'tepid',
  'thorn', 'those', 'three', 'threw', 'throw', 'thrum', 'theme', 'thick',
  'tiger', 'tight', 'timer', 'tipsy', 'titan', 'title', 'toast', 'token',
  'torch', 'total', 'touch', 'tough', 'towel', 'tower', 'toxic', 'trace',
  'track', 'trade', 'trail', 'train', 'trait', 'tramp', 'trash', 'trawl',
  'treat', 'trend', 'trial', 'trick', 'tried', 'troop', 'trout', 'truce',
  'truck', 'truly', 'trump', 'trunk', 'tryst', 'tulip', 'tumor', 'tuner',
  'tuple', 'tweak', 'twice', 'twill', 'twist', 'tying', 'udder', 'ultra',
  'umber', 'uncle', 'under', 'unfit', 'unify', 'union', 'unity', 'unzip',
  'until', 'upper', 'upset', 'urban', 'usher', 'usual', 'utter', 'valor',
  'valve', 'vault', 'verse', 'video', 'vigor', 'viral', 'virus', 'visor',
  'visit', 'vital', 'vivid', 'vocal', 'vodka', 'voice', 'vouch', 'vowel',
  'wager', 'watch', 'water', 'weary', 'weave', 'wedge', 'weigh', 'weird',
  'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'whirl', 'white',
  'whole', 'whose', 'wider', 'widen', 'windy', 'witch', 'woman', 'women',
  'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrath',
  'wreck', 'wring', 'write', 'wrong', 'yacht', 'yearn', 'yield', 'young',
  'youth', 'zebra', 'zilch',
];

// Long words: 8+ characters
const LONG_WORDS: string[] = [
  'absolute', 'abstract', 'abundant', 'academic', 'accepted', 'accurate',
  'achieved', 'acquired', 'activity', 'actually', 'addition', 'adequate',
  'adjacent', 'adjusted', 'adoption', 'advanced', 'affected', 'affirmed',
  'affluent', 'agitated', 'analysis', 'ancestry', 'animated', 'annually',
  'answered', 'apparent', 'appealed', 'appeared', 'appetite', 'applause',
  'approval', 'argument', 'arranged', 'arrested', 'aspiring', 'assessed',
  'asteroid', 'attached', 'attended', 'audience', 'balanced', 'behavior',
  'believed', 'birthday', 'blanched', 'blizzard', 'borrowed', 'boundary',
  'brilliant', 'brochure', 'business', 'calendar', 'captured', 'cardinal',
  'carousel', 'category', 'ceremony', 'champion', 'changed', 'channels',
  'character', 'chemical', 'children', 'chlorine', 'coherent', 'collapse',
  'combined', 'commence', 'complete', 'compound', 'conclude', 'conflict',
  'confused', 'congress', 'constant', 'consumed', 'contains', 'contract',
  'contrast', 'creative', 'criminal', 'critical', 'cultural', 'daylight',
  'deadline', 'deceived', 'decisive', 'declared', 'declined', 'defended',
  'definite', 'delivery', 'describe', 'detailed', 'detected', 'diagonal',
  'directly', 'disaster', 'discount', 'disorder', 'division', 'dolphins',
  'dominant', 'document', 'dramatic', 'duration', 'educated', 'election',
  'elevated', 'embedded', 'emphasis', 'employed', 'engineer', 'enormous',
  'entrance', 'envelope', 'evaluate', 'evidence', 'examined', 'excluded',
  'executed', 'exempted', 'existing', 'expanded', 'expected', 'extended',
  'external', 'faithful', 'familiar', 'feedback', 'fighting', 'flamingo',
  'followed', 'forecast', 'formally', 'frontier', 'function', 'gorgeous',
  'gradient', 'greatest', 'guidance', 'happened', 'harshest', 'haunting',
  'headline', 'heritage', 'highland', 'historic', 'homeless', 'hospital',
  'humanity', 'ideology', 'imagined', 'improved', 'included', 'increase',
  'indicate', 'industry', 'infected', 'infinite', 'informed', 'inspired',
  'instinct', 'interact', 'interest', 'involved', 'isolated', 'judgment',
  'keyboard', 'language', 'launched', 'learning', 'leverage', 'lifetime',
  'location', 'magnetic', 'maintain', 'manifest', 'marriage', 'matching',
  'material', 'measured', 'medicine', 'midnight', 'military', 'minimize',
  'moisture', 'momentum', 'moreover', 'mountain', 'multiple', 'mushroom',
  'navigate', 'negative', 'notebook', 'observed', 'obstacle', 'occupied',
  'occurred', 'obtained', 'opposite', 'optional', 'ordinary', 'outbreak',
  'overcome', 'overview', 'pandemic', 'parallel', 'password', 'patience',
  'peaceful', 'personal', 'pleasant', 'possible', 'powerful', 'prepared',
  'presence', 'previous', 'princess', 'priority', 'probably', 'progress',
  'proposal', 'prospect', 'protocol', 'provided', 'purchase', 'question',
  'randomly', 'received', 'recently', 'required', 'research', 'resource',
  'response', 'revealed', 'reviewed', 'scaffold', 'scenario', 'schedule',
  'security', 'selected', 'sequence', 'shoulder', 'skeleton', 'software',
  'solution', 'somebody', 'somewhat', 'spectrum', 'standard', 'starting',
  'strategy', 'strength', 'strictly', 'struggle', 'stubborn', 'suitable',
  'supposed', 'surprise', 'survived', 'teaching', 'template', 'terminal',
  'thinking', 'thousand', 'together', 'tomorrow', 'training', 'transfer',
  'traveled', 'treasure', 'triangle', 'tropical', 'universe', 'upgraded',
  'valuable', 'variable', 'velocity', 'vertical', 'vertical', 'volcanic',
  'whatever', 'wherever', 'whistled', 'windmill', 'wireless', 'wondered',
  'workshop', 'yourself', 'absolute', 'backbone', 'backfire', 'backyard',
  'balanced', 'baseline', 'bathroom', 'becoming', 'bedrooms', 'beehives',
  'cafeteria', 'candidate', 'carefully', 'cautious', 'clearing', 'climbing',
  'clothing', 'colorful', 'combines', 'commence', 'compiler', 'computer',
  'concrete', 'confined', 'copycat', 'coverage', 'daydream', 'december',
  'dinosaur', 'discover', 'distance', 'dragonfly', 'dramatic', 'dreaming',
  'darkness', 'entrance', 'evolving', 'exciting', 'explicit', 'fabulous',
  'fairness', 'festival', 'floating', 'focusing', 'football', 'freedoms',
  'generate', 'genuine', 'glittery', 'gorgeous', 'grateful', 'grumbled',
  'handsome', 'happened', 'hardwork', 'harmless', 'haunted', 'helpful',
  'historian', 'holistic', 'homework', 'hopeless', 'humorous', 'imaginary',
  'increase', 'innocent', 'integral', 'inventor', 'jealousy', 'keywords',
  'lifelong', 'likewise', 'listener', 'lonesome', 'loveable', 'majestic',
  'managing', 'mechanism', 'medieval', 'memorial', 'menacing', 'mindful',
  'mirrored', 'modeling', 'moderate', 'monument', 'movement', 'narrowed',
  'negative', 'notebook', 'nourished', 'numbered', 'optimize', 'outgoing',
  'outdoors', 'overflow', 'overhear', 'painting', 'palomino', 'paradise',
  'parachute', 'parental', 'perfects', 'pilgrim', 'pipeline', 'platform',
  'playback', 'practice', 'precious', 'pregnant', 'producing', 'profound',
  'programming', 'radiator', 'rational', 'realized', 'recorded', 'reducing',
  'reformed', 'regarded', 'reliable', 'remember', 'reminder', 'reported',
  'resulted', 'romantic', 'rotating', 'sandwich', 'sleeping', 'slippery',
  'snapshot', 'specific', 'spelling', 'spending', 'spinning', 'splendid',
  'spotless', 'sprinted', 'stacking', 'standing', 'starfish', 'stargazed',
  'stumbled', 'stunning', 'sunflower', 'supplies', 'survived', 'swimming',
  'terrific', 'throwing', 'thinking', 'thriller', 'together', 'tortoise',
  'touching', 'towering', 'tracking', 'treating', 'truthful', 'umbrella',
  'uncommon', 'underway', 'unlikely', 'unsigned', 'upcoming', 'upstream',
  'vacation', 'validate', 'vehicles', 'ventures', 'vigilant', 'visiting',
  'wandered', 'watching', 'waterfall', 'weekends', 'welcomed', 'whistler',
  'wristlet', 'youthful', 'zeppelin',
];

const WORD_TIERS: Record<WordTier, string[]> = {
  short: SHORT_WORDS,
  medium: MEDIUM_WORDS,
  long: LONG_WORDS,
};

// Size-based word pools:
// Small enemies get words ≤5 chars; 6-char words included so they can go to either size.
// Large enemies get words ≥7 chars; 6-char words included so they can go to either size.
const SMALL_WORD_POOL: string[] = [...SHORT_WORDS, ...MEDIUM_WORDS].filter(w => w.length <= 6);
const LARGE_WORD_POOL: string[] = [...MEDIUM_WORDS, ...LONG_WORDS].filter(w => w.length >= 6);

// Set of words currently assigned to active rockets
const activeWords = new Set<string>();

/**
 * Returns a random word from the given tier that is not currently in use.
 * Throws if all words in the tier are exhausted.
 */
export function getWord(tier: WordTier): string {
  const pool = WORD_TIERS[tier];
  const available = pool.filter((w) => !activeWords.has(w));
  if (available.length === 0) {
    throw new Error(`No available words in tier "${tier}"`);
  }
  const word = available[Math.floor(Math.random() * available.length)];
  activeWords.add(word);
  return word;
}

/**
 * Returns a random word appropriate for the given enemy size.
 * Small enemies: words ≤5 chars (6-char words included so they can randomly land on either size).
 * Large enemies: words ≥7 chars (6-char words included so they can randomly land on either size).
 * Throws if the pool for the given size is exhausted.
 */
export function getWordForSize(size: 'small' | 'large'): string {
  const pool = size === 'small' ? SMALL_WORD_POOL : LARGE_WORD_POOL;
  const available = pool.filter(w => !activeWords.has(w));
  if (available.length === 0) {
    throw new Error(`No available words for size "${size}"`);
  }
  const word = available[Math.floor(Math.random() * available.length)];
  activeWords.add(word);
  return word;
}

/**
 * Releases a word so it can be assigned to a new rocket.
 */
export function releaseWord(word: string): void {
  activeWords.delete(word);
}

/**
 * Returns the number of words available in each tier (for debugging/testing).
 */
export function getWordCounts(): Record<WordTier, number> {
  return {
    short: SHORT_WORDS.length,
    medium: MEDIUM_WORDS.length,
    long: LONG_WORDS.length,
  };
}
